#
# Copyright contributors to the Galasa project 
#
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-external
  labels:
    app: {{ .Release.Name }}-api-external
spec:
  type: NodePort
  ports:
  - port: 9010
    name: metrics
  - port: 9011
    name: health
  - port: 8080
    name: http
  selector:
    app: {{ .Release.Name }}-api
