#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#
# Creates the "galasa" ServiceAccount and associated Role and RoleBinding if the ServiceAccount doesn't already exist,
# or if the ServiceAccount was set up by Helm.
#
# When a "helm upgrade" is issued, Helm applies any changes to the YAML templates. Having the additional check to make
# sure that the ServiceAccount was created by Helm means that this template will not be rendered as an empty template,
# which would otherwise cause Helm to delete these resources.
#
# These resources are defined as Helm hooks that are loaded first, so they can be used by other hooks if needed.
{{- $serviceAccount := (lookup "v1" "ServiceAccount" .Release.Namespace "galasa") }}
{{- $isServiceAccountOwnedByHelm := false }}

{{- if $serviceAccount }}
{{- if $serviceAccount.metadata }}
{{- if $serviceAccount.metadata.labels }}
{{- $isServiceAccountOwnedByHelm = (eq (index $serviceAccount.metadata.labels "app.kubernetes.io/instance") .Release.Name) }}
{{- end }}
{{- end }}
{{- end }}

{{- if or (not $serviceAccount) $isServiceAccountOwnedByHelm }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: galasa
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: {{ .Release.Name | quote }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: galasa
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: {{ .Release.Name | quote }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","create","update","patch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","patch","list","watch","update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","list","create","delete"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: galasa
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
    helm.sh/resource-policy: keep
    meta.helm.sh/release-name: {{ .Release.Name | quote }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace | quote }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
roleRef:
  kind: Role
  name: galasa
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: galasa

{{- end }}
