#
# Copyright contributors to the Galasa project
#
# SPDX-License-Identifier: EPL-2.0
#

apiVersion: v2
name: ecosystem
description: Galasa Ecosystem
type: application
#
home: "galasa.dev"
#
version: "0.46.1"
